---
- name: Stress Testing Remote
  hosts: hosts
  gather_facts: True
  vars:
    ansible_port: 22
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: /home/theseus/.ssh/P10-aws.pem
  tasks:
    - name: Stress Testing
      shell:
        cmd: stress --cpu 9 --timeout 600
---