version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 10.0.0.2:3306
      WORDPRESS_DB_USER: theseus
      WORDPRESS_DB_PASSWORD: theseus
      WORDPRESS_DB_NAME: WordPress
    volumes:
      - /home/theseus/wordpress/:/var/www/html/
